version: "3.9"
services:
  postgres:
    image: postgres:14-alpine
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./data/postgres/entrypoint.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: neomaind
      POSTGRES_PASSWORD: s4cr4tP@ss123!
    ports:
      - 5432:5432

volumes:
    postgres:
